services:
  mongo-service1:
    image: nguyenlthoe/mongodb-server:1.0.0
    container_name: mongodb-server-cf-1
    hostname: mongodb-server-cf-1
    ports:
      - 27017:27017
    volumes:
      - ./mongod-1.conf:/opt/mongod.conf
      - ./mongo-key:/opt/mongo-key
    networks:
      mongo-cluster:
        ipv4_address: 172.25.0.5
  mongo-service2:
    image: nguyenlthoe/mongodb-server:1.0.0
    container_name: mongodb-server-cf-2
    hostname: mongodb-server-cf-2
    volumes:
      - ./mongod-2.conf:/opt/mongod.conf
      - ./mongo-key:/opt/mongo-key
    ports:
      - 27018:27017
    networks:
      mongo-cluster:
        ipv4_address: 172.25.0.6
  mongo-service3:
    image: nguyenlthoe/mongodb-server:1.0.0
    container_name: mongodb-server-cf-3
    hostname: mongodb-server-cf-3
    volumes:
      - ./mongod-3.conf:/opt/mongod.conf
      - ./mongo-key:/opt/mongo-key
    ports:
      - 27019:27017
    networks:
      mongo-cluster:
        ipv4_address: 172.25.0.7
networks:
  mongo-cluster:
      external:
        name: custom_network